name: Bug Report
description: File a bug report
title: "[Bug Report]: <title>"
labels: "bug report"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Your contact details
      description: Please list your e-mail in order for us to reach out if necessary.
      placeholder: email@example.com
    validations:
      required: false
  - type: input
    id: subject
    attributes:
      label: Subject
      description: Please add a relevant subject for the bug you are experiencing.
    validations:
      required: true
  - type: textarea
    id: what-issue
    attributes:
      label: What issue are you facing?
      description: Also tell us, what the expeceted outcome was?
      placeholder: "Please describe the bug you have encountered as detailed as possible"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: What are the steps to reproduce this bug?
      description: "Please provide the steps to reproduce this bug. The more detailed the better!"
      placeholder: "technologies: 
      - "tech1, tech2"
      - "sdfsdf"
    validations:
      required: false
  - type: textarea
    id: provide-logs
    attributes:
      label: Can you provide any relevant logs or output?
      description: "Please provide logs or output"
      placeholder: "Please provide logs or output to illustrate this issue. Please only provide non-sensitive data"
    validations:
      required: true
  - type: dropdown
    id: blocking
    attributes:
      label: Blocking
      description: Is this issue blocking you from using Qapio?
      options:
        - non-blocking
        - blocking
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://qapio.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
