name: Bug Report
description: File a bug report
title: "[Bug Report]: <title>"
labels: "bug report"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: existing_issue
    attributes:
      label: Is there an existing similar issue?
      description: Please search for similar existing and solved issues before committing yours.
      options:
        - label: I have searched for similar issues, but haven't found any equivalent.
          required: true
  - type: input
    id: contact
    attributes:
      label: Your contact details
      description: Please list your e-mail in order for us to reach out if necessary.
      placeholder: email@example.com
    validations:
      required: false
  - type: input
    id: subject
    attributes:
      label: Subject
      description: Please add a relevant subject for the bug you are experiencing.
    validations:
      required: true
  - type: dropdown
    id: type_of_issue
    attributes:
      options:
        - Transient - Occuring only once
        - Intermittent - Occuring irregularly
        - Permanent - Occuring repeeatedly
    validations:
      required: false
  - type: dropdown
    id: blocking
    attributes:
      label: Blocking
      description: Is this issue blocking you from using Qapio?
      options:
        - non-blocking
        - blocking
    validations:
      required: false
      
  - type: input
    id: last_working_date
    attributes:
      label: Last working date
      description: When was the last known working date?
    validations:
      required: false      
  - type: textarea
    id: what-issue
    attributes:
      label: What issue are you facing?
      description: Also tell us, what the expeceted outcome was?
      placeholder: "Please describe the bug and the expected out you have encountered as detailed as possible"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: What are the steps to reproduce this bug?
      description: "Please provide the steps to reproduce this bug. The more detailed the better!"
      placeholder: |
        Step 1:
        Step 2:
        Step 3:
    validations:
      required: false
  - type: textarea
    id: provide-logs
    attributes:
      label: Can you provide any relevant logs or output?
      description: Please provide logs or output to illustrate your issue. Please only provide non-sensitive data"
      placeholder: "Click here and then drag and drop your attachments"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
